### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by iuriaranda**
See readme for the full details.

### CODE REVIEW

**Review by duboisph — APPROVED** [review]

**Review by simonrondelez — APPROVED** [review]
not the best way to handle lambda source code but i guess for this small usecase its ok.

**Comment by duboisph** [comment]
@simonrondelez I'm curious now, what would you do?

**Comment by iuriaranda** [comment]
I'm also curious 😅

**Comment by simonrondelez** [comment]
imo its better to split the code logic from the terraform logic. So store the lambda code in a s3 bucket and use that as a source in the lambda function. 

In this case its maybe not relevant since it won't change often.

**Pull request merged**
